In [1]:
from newton import *
import numpy as np

In [7]:
def f(x):
    return x**2

In [8]:
jacobian(f, 3)

array([[6.00000002]])

In [12]:
x, y = newton(f, np.array([2, 3]))

In [13]:
x

[array([2, 3]),
 array([1. , 1.5]),
 array([0.5 , 0.75]),
 array([0.25 , 0.375]),
 array([0.125 , 0.1875]),
 array([0.0625 , 0.09375]),
 array([0.03125 , 0.046875]),
 array([0.015625 , 0.0234375]),
 array([0.0078125 , 0.01171875]),
 array([0.00390625, 0.00585938]),
 array([0.00195312, 0.00292969]),
 array([0.00097656, 0.00146484]),
 array([0.00048828, 0.00073242])]

In [14]:
y

[array([4, 9]),
 array([1.        , 2.25000001]),
 array([0.25  , 0.5625]),
 array([0.0625  , 0.140625]),
 array([0.015625  , 0.03515625]),
 array([0.00390625, 0.00878906]),
 array([0.00097656, 0.00219727]),
 array([0.00024414, 0.00054932]),
 array([6.10351560e-05, 1.37329102e-04]),
 array([1.52587890e-05, 3.43322756e-05]),
 array([3.81469725e-06, 8.58306890e-06]),
 array([9.53674312e-07, 2.14576722e-06]),
 array([2.38418578e-07, 5.36441807e-07])]